update

diff --git a/chklnks b/chklnks
--- a/chklnks
+++ b/chklnks
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: chklnks,v 1.9 2016/04/14 11:09:07 fulford Exp fulford $
+# $Id: chklnks,v 1.10 2016/04/14 11:38:12 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/chklnks,v $
-# $Revision: 1.9 $
+# $Revision: 1.10 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -19,17 +19,22 @@ while [ $# -gt 0 ] ;do
 done
 action=${action:-"echo"}
 path=${path:-"./"}
-sudo find -L $path -type l -print|
-while read f ;do
-	if [ $action == "delete" ];then
-		if rm $f ;then 
-			if [ $verbose ];then
-				echo "$cmd: $f dead link removed" >&2
+for d in $path;do
+	if [ $verbose ];then
+		echo "$cmd: checking directory $d"
+	fi
+	sudo find -L $d -type l -print|
+	while read f ;do
+		if [ $action == "delete" ];then
+			if rm $f ;then 
+				if [ $verbose ];then
+					echo "$cmd: $f dead link removed" >&2
+				fi
+			else
+				echo "$cmd: could not remove $f" >&2
 			fi
 		else
-			echo "$cmd: could not remove $f" >&2
-		fi
-	else
 			$action "$cmd: found dead link $f" >&2
-	fi
+		fi
+	done
 done
