update

diff --git a/chklnks b/chklnks
--- a/chklnks
+++ b/chklnks
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: chklnks,v 1.100 2016/04/19 08:31:54 fulford Exp fulford $
+# $Id: chklnks,v 1.101 2016/04/19 08:39:52 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/chklnks,v $
-# $Revision: 1.100 $
+# $Revision: 1.101 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0709 229 5385
 ########################################################################
 cmd=`basename $0`
-syntax="$cmd [-a] [-d] [-h <hostid> [-r] [-v] [<dir_name> <dir_name> ....]|[-V]"
+syntax="$cmd [-d] [-h <hostid> [-r] [-v] [[-a]|[<dir_name> <dir_name> ....]]|[-V]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-a) all=1;shift;;
@@ -16,13 +16,17 @@ while [ $# -gt 0 ] ;do
 		-h) hostid=$2;shift 2;;
 		-r) action=delete;shift;;
 		-v) verbose=0;shift;;
-		-V) echo "$cmd $Revision: 1.100 $ $Date: 2016/04/19 08:31:54 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.101 $ $Date: 2016/04/19 08:39:52 $"|awk '{print $1,$3,$6}';exit;;  
 		 /*) paths="$paths $1";shift;;
 	 	*) echo "$syntax" >&2;exit;;
 	esac
 done
 action=${action:-"echo"}
 all=${all:=0}
+[ $all -a -n "$paths" ] &&{
+	echo "$cmd: can't specify directories with the -a option" >&2
+	echo "$syntax" >&2
+}
 tdf=/tmp/df-$$
 tmounts=/tmp/mounts-$$
 verbose=${verbose:-1}
